//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWebSite.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActorMovy
    {
        public decimal ActorMovieId { get; set; }
        public decimal ActorId { get; set; }
        public decimal MovieId { get; set; }
        public System.DateTimeOffset CreatedDateTime { get; set; }
        public System.DateTimeOffset LastModifiedDateTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tblActor tblActor { get; set; }
        public virtual tblMovy tblMovy { get; set; }
    }
}
