//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWebSite.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblActor()
        {
            this.tblActorMovies = new HashSet<tblActorMovy>();
        }
    
        public decimal ActorId { get; set; }
        public string ActorName { get; set; }
        public byte GenderId { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Bio { get; set; }
        public System.DateTimeOffset CreatedDateTime { get; set; }
        public System.DateTimeOffset LastModifiedDateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public decimal ImageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActorMovy> tblActorMovies { get; set; }
        public virtual tblGender tblGender { get; set; }
        public virtual tblImage tblImage { get; set; }
    }
}
