//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWebSite.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMovy()
        {
            this.tblActorMovies = new HashSet<tblActorMovy>();
        }
    
        public string MovieName { get; set; }
        public decimal MovieId { get; set; }
        public int YearOfRelease { get; set; }
        public string Plot { get; set; }
        public decimal ProducerId { get; set; }
        public System.DateTimeOffset CreatedDateTime { get; set; }
        public System.DateTimeOffset LastModifiedDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public decimal ImageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActorMovy> tblActorMovies { get; set; }
        public virtual tblImage tblImage { get; set; }
        public virtual tblProducer tblProducer { get; set; }
    }
}
